"""Migration name

Revision ID: 8f15d8a1a2ed
Revises:
Create Date: 2025-03-09 10:11:35.466010

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8f15d8a1a2ed"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
