"""some change enum2

Revision ID: 9f312837f148
Revises: 71bef58018c1
Create Date: 2025-03-14 17:39:33.360221

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f312837f148"
down_revision: Union[str, None] = "71bef58018c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("applications", "owner", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "applications", "can_contact", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "applications", "can_contact", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("applications", "owner", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
