"""add text qiestinon

Revision ID: d84b44d45c1e
Revises: 27c8dbcec442
Create Date: 2025-03-12 00:54:35.176937

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d84b44d45c1e"
down_revision: Union[str, None] = "27c8dbcec442"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("text_application", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "text_application")
    # ### end Alembic commands ###
