"""add message id

Revision ID: eb613c5d975f
Revises: 65e8836c6731
Create Date: 2025-03-12 18:41:10.370299

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb613c5d975f"
down_revision: Union[str, None] = "65e8836c6731"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("admin_message_ids", sa.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "admin_message_ids")
    # ### end Alembic commands ###
